// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Role struct {
	ID          string
	RoleName    string
	Description sql.NullString
	Permissions []byte
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID            string
	Email         string
	Username      string
	PasswordHash  string
	IsActive      sql.NullBool
	EmailVerified sql.NullBool
	LastLogin     sql.NullTime
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type UserDetail struct {
	ID          string
	UserID      string
	FullName    sql.NullString
	Phone       sql.NullString
	Address     sql.NullString
	DateOfBirth sql.NullTime
	AvatarUrl   sql.NullString
	Bio         sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type UserRole struct {
	ID         string
	UserID     string
	RoleID     string
	AssignedAt sql.NullTime
	AssignedBy sql.NullString
}
