// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Role struct {
	ID          int32
	RoleName    string
	Description sql.NullString
	Permissions []byte
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID            int32
	Email         string
	Username      string
	PasswordHash  string
	IsActive      sql.NullBool
	EmailVerified sql.NullBool
	LastLogin     sql.NullTime
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type UserDetail struct {
	ID          int32
	UserID      int32
	FullName    sql.NullString
	Phone       sql.NullString
	Address     sql.NullString
	DateOfBirth sql.NullTime
	AvatarUrl   sql.NullString
	Bio         sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type UserRole struct {
	ID         int32
	UserID     int32
	RoleID     int32
	AssignedAt sql.NullTime
	AssignedBy sql.NullInt32
}
