// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_roles.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const assignRoleToUser = `-- name: AssignRoleToUser :one
INSERT INTO user_roles (user_id, role_id, assigned_by)
VALUES ($1, $2, $3)
RETURNING id, user_id, role_id, assigned_at, assigned_by
`

type AssignRoleToUserParams struct {
	UserID     int32
	RoleID     int32
	AssignedBy sql.NullInt32
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, assignRoleToUser, arg.UserID, arg.RoleID, arg.AssignedBy)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.AssignedAt,
		&i.AssignedBy,
	)
	return i, err
}

const checkUserHasAnyRole = `-- name: CheckUserHasAnyRole :one
SELECT EXISTS(
    SELECT 1 FROM user_roles ur
    INNER JOIN roles r ON ur.role_id = r.id
    WHERE ur.user_id = $1 AND r.role_name = ANY($2::text[])
) as has_any_role
`

type CheckUserHasAnyRoleParams struct {
	UserID  int32
	Column2 []string
}

func (q *Queries) CheckUserHasAnyRole(ctx context.Context, arg CheckUserHasAnyRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserHasAnyRole, arg.UserID, pq.Array(arg.Column2))
	var has_any_role bool
	err := row.Scan(&has_any_role)
	return has_any_role, err
}

const checkUserHasRole = `-- name: CheckUserHasRole :one
SELECT EXISTS(
    SELECT 1 FROM user_roles ur
    INNER JOIN roles r ON ur.role_id = r.id
    WHERE ur.user_id = $1 AND r.role_name = $2
) as has_role
`

type CheckUserHasRoleParams struct {
	UserID   int32
	RoleName string
}

func (q *Queries) CheckUserHasRole(ctx context.Context, arg CheckUserHasRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserHasRole, arg.UserID, arg.RoleName)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.role_name, r.description, r.permissions, r.created_at, r.updated_at FROM roles r
INNER JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int32) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllUserRoles = `-- name: RemoveAllUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) RemoveAllUserRoles(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, removeAllUserRoles, userID)
	return err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID int32
	RoleID int32
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}
