// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_details.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUserDetails = `-- name: CreateUserDetails :one
INSERT INTO user_details (user_id, full_name, phone, address, date_of_birth, avatar_url, bio)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, full_name, phone, address, date_of_birth, avatar_url, bio, created_at, updated_at
`

type CreateUserDetailsParams struct {
	UserID      string
	FullName    sql.NullString
	Phone       sql.NullString
	Address     sql.NullString
	DateOfBirth sql.NullTime
	AvatarUrl   sql.NullString
	Bio         sql.NullString
}

func (q *Queries) CreateUserDetails(ctx context.Context, arg CreateUserDetailsParams) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, createUserDetails,
		arg.UserID,
		arg.FullName,
		arg.Phone,
		arg.Address,
		arg.DateOfBirth,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.Address,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDetailsByUserID = `-- name: GetUserDetailsByUserID :one
SELECT id, user_id, full_name, phone, address, date_of_birth, avatar_url, bio, created_at, updated_at FROM user_details WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserDetailsByUserID(ctx context.Context, userID string) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, getUserDetailsByUserID, userID)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.Address,
		&i.DateOfBirth,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE user_details
SET avatar_url = $2, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateUserAvatarParams struct {
	UserID    string
	AvatarUrl sql.NullString
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.UserID, arg.AvatarUrl)
	return err
}

const updateUserDetails = `-- name: UpdateUserDetails :exec
UPDATE user_details
SET full_name = COALESCE(NULLIF($2, ''), full_name),
    phone = COALESCE(NULLIF($3, ''), phone),
    address = COALESCE(NULLIF($4, ''), address),
    date_of_birth = COALESCE($5, date_of_birth),
    bio = COALESCE(NULLIF($6, ''), bio),
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateUserDetailsParams struct {
	UserID      string
	FullName    sql.NullString
	Phone       sql.NullString
	Address     sql.NullString
	DateOfBirth sql.NullTime
	Bio         sql.NullString
}

func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDetails,
		arg.UserID,
		arg.FullName,
		arg.Phone,
		arg.Address,
		arg.DateOfBirth,
		arg.Bio,
	)
	return err
}
